include config.mk

.PHONY: all
all: $(BINARY)

.PHONY: dev
dev: all test

$(BINARY): $(SOURCES) $(LIBTERMKEYLIB) $(LIBWED) wed.o
	$(CC) wed.o $(LIBWED) $(LIBTERMKEYLIB) -o $@ $(LDFLAGS)

$(LIBWED): $(OBJECTS)
	$(AR) rcs $(LIBWED) $(LIBOBJECTS)

$(LIBTERMKEYLIB):
	$(MAKE) -C $(LIBTERMKEYDIR)

.c.o:
	$(CC) -c $(CFLAGS) $< -o $@

.cc.o:
	$(CXX) -c $(CXXFLAGS) $< -o $@

-include $(DEPENDENCIES)

config_scan.o: config_scan.c config_parse.c

config_scan.c: config_scan.l
	$(FLEX) -o $@ $^

config_parse.c: config_parse.y
	$(BISON) -y -d -o $@ $^

$(STATIC_SOURCES): build_config.h

build_config.h:
	@echo '/* Autogenerated by Makefile */' > build_config.h
	@echo '#ifndef WED_BUILD_CONFIG_H' >> build_config.h
	@echo '#define WED_BUILD_CONFIG_H' >> build_config.h
	@echo '#define WED_DEV $(WED_DEV)' >> build_config.h
	@echo '#define WEDRUNTIME "$(DESTDIR)$(WEDRUNTIME)"' >> build_config.h
	@echo '#define WED_VERSION "$(WED_VERSION)"' >> build_config.h
	@echo '#define WED_VERSION_LONG "$(WED_VERSION_LONG)"' >> build_config.h
	@echo '#define WED_BUILD_DATETIME "$(WED_BUILD_DATETIME)"' >> build_config.h
	@echo '#define WED_PCRE_VERSION_GE_8_20 $(WED_PCRE_VERSION_GE_8_20)' >> build_config.h
	@echo '#define WED_SOURCE_HIGHLIGHT $(WED_SOURCE_HIGHLIGHT)' >> build_config.h
	@echo '#endif' >> build_config.h

test: $(BINARY) $(TESTS)
	@echo 'Running code tests:'
	@prove -e '' tests/code
	@echo 'Running text tests:'
	@tests/text/run_text_tests.sh
	@touch test

-include $(TESTDEPENDENCIES)

tests/code/%.t: tests/code/%.c tests/code/tap.o $(LIBWED) $(LIBTERMKEYLIB)
	$(CC) $(CFLAGS) $< tests/code/tap.o $(LIBWED) $(LIBTERMKEYLIB) -o $@

tests/code/tap.o:
	$(CC) -c $(CFLAGS) tests/code/tap.c -o $@

.PHONY: clean
clean:
	rm -f *.o *.d $(LIBWED) $(BINARY) config_parse.c config_parse.h config_scan.c build_config.h
	rm -f tests/code/*.o tests/code/*.t tests/code/*.d
	$(MAKE) -C $(LIBTERMKEYDIR) clean

.PHONY: install
install:
	@echo 'Installing wed under $(DESTDIR)$(PREFIX)'
	@mkdir -p $(DESTDIR)$(PREFIX)/bin
	@install -m755 -s $(BINARY) $(DESTDIR)$(PREFIX)/bin
	@install -m755 '$(WEDCLIPBOARD)' $(DESTDIR)$(PREFIX)/bin
	@install -m755 -d $(DESTDIR)$(WEDRUNTIME)	
	@cp -fr wedruntime/* $(DESTDIR)$(WEDRUNTIME)
	@find $(DESTDIR)$(WEDRUNTIME) -type f -exec chmod 644 {} \;
	@mkdir -p $(DESTDIR)$(PREFIX)/share/man/man1
	@sed 's/VERSION/$(WED_VERSION)/g' doc/man/wed.1 | gzip > $(DESTDIR)$(PREFIX)/share/man/man1/wed.1.gz
	@chmod 644 $(DESTDIR)$(PREFIX)/share/man/man1/wed.1.gz

.PHONY: uninstall
uninstall:
	@echo 'Uninstalling wed'
	@rm -f $(DESTDIR)$(PREFIX)/bin/$(BINARY)
	@rm -f '$(DESTDIR)$(PREFIX)/bin/$(WEDCLIPBOARD)'
	@rm -fr $(DESTDIR)$(WEDRUNTIME)
	@rm -f $(DESTDIR)$(PREFIX)/share/man/man1/wed.1.gz
