.TH TERMKEY_SET_WAITTIME 3
.SH NAME
termkey_set_waittime, termkey_get_waittime \- control the wait time for multibyte sequences
.SH SYNOPSIS
.nf
.B #include <termkey.h>
.sp
.BI "void termkey_set_waittime(TermKey *" tk ", int " msec );
.BI "int termkey_get_waittime(TermKey *" tk );
.fi
.sp
Link with \fI-ltermkey\fP.
.SH DESCRIPTION
\fBtermkey_set_waittime\fP() sets the number of miliseconds that \fBtermkey_waitkey\fP(3) will wait for the remaining bytes of a multibyte sequence if it detects the start of a partially-complete one.
.PP
\fBtermkey_get_waittime\fP() returns the value set by the last call to \fBtermkey_set_waittime\fP(), or the default value if a different has not been set.
.SH "RETURN VALUE"
\fBtermkey_set_waittime\fP() returns no value. \fBtermkey_get_waittime\fP() returns the current wait time in miliseconds.
.SH "SEE ALSO"
.BR termkey_getkey (3),
.BR termkey_waitkey (3),
.BR termkey (7)
