.TH TERMKEY_CANONICALISE 3
.SH NAME
termkey_canonicalise \- canonicalise a key event
.SH SYNOPSIS
.nf
.B #include <termkey.h>
.sp
.BI "void termkey_canonicalise(TermKey *" tk ", TermKeyKey *" key );
.fi
.sp
Link with \fI-ltermkey\fP.
.SH DESCRIPTION
\fBtermkey_canonicalise\fP(3) modifies the key event structure given by \fIkey\fP according to the canonicalisation flags set on the given \fBtermkey\fP instance. This operation is performed implicitly by \fBtermkey_getkey\fP(3), \fBtermkey_waitkey\fP(3) and \fBtermkey_strpkey\fP(3), and is also provided explicitly by this function.
.PP
See \fBtermkey\fP(7) for a list of canonicalisation flags.
.SH "RETURN VALUE"
\fBtermkey_canonicalise\fP() returns no value.
.SH "SEE ALSO"
.BR termkey_set_canonflags (3),
.BR termkey_waitkey (3),
.BR termkey_strpkey (3),
.BR termkey (7)
