.TH WED 1 "6 Feb 2016" "VERSION"
.SH NAME
wed \- Windows terminal EDitor
.SH SYNOPSIS
.B wed
[OPTIONS] [FILE]...
.SH DESCRIPTION
.B wed
is a terminal text editor with key bindings commonly used in Windows based editors.
.SH OPTIONS
.TP
\fB\-c, \-\-config-file\fP \fIWEDRC\fP
Load the \fIWEDRC\fP config file after all other config files have been processed.
.TP
.B \-h, \-\-help
Print help message and exit.
.TP
\fB\-k, \-\-key-string\fP \fIKEYSTR\fP
Process \fIKEYSTR\fP string representation of key presses after initialisation.
.TP
.B \-v, \-\-version
Print version information and exit.
.SH AUTHOR
Richard Burke <rich.g.burke at gmail dot com>
